# Generated by Django 4.2.4 on 2023-08-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200000000000000),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
