# Generated by Django 4.2.4 on 2023-08-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_question_text_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_body',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
